catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
  vitest: 4.1.10

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.18.0.cjs
