import { describe, expect, it } from "vitest";
import corpus from "../quiz/corpus.json";
import { formTable, formsFor, type WordType } from "../quiz/forms.js";

/**
 * Is every word in the shipped corpus actually askable?
 *
 * The corpus is generated by `scripts/build-corpus.mjs` and committed, so
 * nothing regenerates it on a normal build — which means a bad entry would sit
 * there until a player met it mid-game. These run on every CI pass against the
 * real conjugator, so the file cannot drift away from the code that reads it.
 */

const words = corpus.words as {
  id: string;
  kana: string;
  kanji?: string;
  pos: string;
  type: string;
  verbClass?: string;
  jlpt?: number;
  gloss: string;
}[];

describe(`corpus integrity`, () => {
  it(`ships a non-trivial number of words`, () => {
    // WHY: a build that silently produced an empty or tiny corpus would leave
    // every session with nothing to ask. This is the smoke test for that.
    expect(words.length).toBeGreaterThan(5000);
  });

  it(`conjugates every single entry`, () => {
    // WHY: this is the guarantee the whole corpus rests on. An entry the
    // conjugator cannot inflect becomes a question with no correct answer, and
    // the round could only ever time out. Checking all of them rather than a
    // sample, because one bad word is one broken round.
    const failures = words
      .filter((w) => formTable(w.kana, [w.pos]) === null)
      .map((w) => `${w.kanji ?? w.kana} (${w.pos})`);
    expect(failures).toEqual([]);
  });

  it(`produces every form its word type promises`, () => {
    // WHY: `formsFor` tells the generator which forms it may ask for. If a word
    // is missing one of them, the generator can pick a form that word cannot
    // produce — the same broken round, reached a different way.
    const failures: string[] = [];
    for (const word of words) {
      const table = formTable(word.kana, [word.pos]);
      if (table === null) continue;
      for (const form of formsFor(word.type as WordType)) {
        if (table.casual[form] === undefined) {
          failures.push(
            `${word.kanji ?? word.kana} (${word.pos}) missing ${form}`
          );
        }
      }
    }
    expect(failures.slice(0, 10)).toEqual([]);
  });

  it(`gives every entry the fields the quiz reads`, () => {
    // WHY: the question embed prints the reading, the class and the gloss. A
    // missing field would render as "undefined" to the channel.
    const bad = words.filter(
      (w) =>
        typeof w.id !== `string` ||
        typeof w.kana !== `string` ||
        w.kana === `` ||
        typeof w.gloss !== `string` ||
        (w.type === `verb` && w.verbClass === undefined)
    );
    expect(bad.slice(0, 5)).toEqual([]);
  });

  it(`keeps JLPT levels within the N5–N1 range`, () => {
    // WHY: the level filter compares numerically, with 5 easiest. A level
    // outside 1–5 would be unreachable by any filter the commands can express.
    const bad = words.filter(
      (w) => w.jlpt !== undefined && (w.jlpt < 1 || w.jlpt > 5)
    );
    expect(bad).toEqual([]);
  });

  it(`holds enough N5 words for a session to be varied`, () => {
    // WHY: N5 is the club's main use case and the default filter. The Waller
    // list caps what is reachable here, so this guards the floor rather than
    // asserting a target — if a pipeline change halved it, sessions would start
    // repeating and nothing else would notice.
    const n5 = words.filter((w) => w.jlpt === 5);
    expect(n5.length).toBeGreaterThan(150);
  });

  it(`excludes vulgar and archaic register`, () => {
    // WHY: the bot posts these into a shared club channel. JMdict files うんこ
    // under `chn` rather than `vulg`, so the exclusion list has to cover both
    // — this is the regression guard for that specific surprise.
    const surfaces = new Set(words.map((w) => w.kana));
    const present = [`うんこ`, `ウンチ`].filter((c) => surfaces.has(c));
    expect(present).toEqual([]);
  });

  it(`records which JMdict release produced it`, () => {
    // WHY: the corpus is committed and rebuilt by hand. Without the source tag
    // there is no way to tell which dictionary a checked-in file came from.
    expect(corpus.source).toMatch(/^\d+\.\d+\.\d+/u);
    expect(corpus.variant).toBe(`common`);
  });
});
